angular-build:
  image: node:20
  script:
    - cd angular
    - yarn install --frozen-lockfile
    - ./node_modules/.bin/ng version
    - node --max-old-space-size=4096 ./node_modules/.bin/ng b -c production --progress
  artifacts:
    when: always
    paths:
      - angular/dist/bookkeeper
    expire_in: 1 day
  cache:
    paths:
      - angular/node_modules/
  only:
    refs:
      - merge_requests
      - main
    changes:
      - angular/**/*

angular-docker:
  tags:
    - docker
  image: docker:latest
  services:
    - docker:dind
  script:
    - ./angular/build_docker.sh
  needs:
    - angular-build
  only:
    refs:
      - main
    changes:
      - angular/**/*
