go-test:
  image: docker.docqube.de/docker/golang:latest
  variables:
    GOOS: linux
    GOARCH: amd64
    CGO_ENABLED: 0
  script:
    - cd go
    - make test
  dependencies: []
  only:
    refs:
      - merge_requests
      - main
    changes:
      - "go/**/*"

go-build:
  image: docker.docqube.de/docker/golang:latest
  variables:
    GOOS: linux
    GOARCH: amd64
    CGO_ENABLED: 0
  script:
    - cd go
    - make build
  artifacts:
    expire_in: 1 hour
    paths:
      - go/build/bookkeeper-api
  needs:
    - go-test
  only:
    refs:
      - merge_requests
      - main
    changes:
      - "go/**/*"

go-docker:
  tags:
    - docker
  image: docker:latest
  services:
    - docker:dind
  script:
    - ./go/build_docker.sh
  needs:
    - go-build
  only:
    refs:
      - main
    changes:
      - go/**/*
