#!/bin/sh

cd go

docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
VERSION=$CI_COMMIT_SHORT_SHA
docker build -t $REGISTRY_URL/$PROJECT_GROUP/api:$VERSION -t $REGISTRY_URL/$PROJECT_GROUP/api:latest .
docker push $REGISTRY_URL/$PROJECT_GROUP/api:$VERSION
docker push $REGISTRY_URL/$PROJECT_GROUP/api:latest
