name: angular

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/angular.yaml"
      - "angular/**"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/angular.yaml"
      - "angular/**"

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' || github.ref == 'refs/heads/main' }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v3.5.3

      - uses: actions/setup-node@v3.6.0
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: "angular/yarn.lock"

      - name: build angular app
        run: |
          cd angular/
          yarn install --frozen-lockfile
          ./node_modules/.bin/ng build --configuration production --progress
          cp -r src/assets dist/bookkeeper
          cp -r manifest.json dist/bookkeeper

      - name: upload artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: artifact
          path: angular/dist/bookkeeper/

  docker:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' || github.ref == 'refs/heads/main' }}
    needs: [build]
    steps:
      - name: checkout repository
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0

      - name: determine service version
        run: echo "VERSION=$(git log -n 1 --no-merges --format=format:%h angular/)" >> $GITHUB_ENV

      - name: download artifact
        uses: actions/download-artifact@v3.0.2
        with:
          name: artifact
          path: angular/dist/bookkeeper/

      - name: build and push image
        uses: docker/build-push-action@v4.1.0
        with:
          context: angular/
          tags: |
            ghcr.io/docqube/bookkeeper/frontend:latest
            ghcr.io/docqube/bookkeeper/frontend:${{ env.VERSION }}
          push: true
