name: angular

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/angular.yaml"
      - "angular/**"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/angular.yaml"
      - "angular/**"

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' || github.ref == 'refs/heads/main' }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: "angular/yarn.lock"

      - name: build angular app
        run: |
          cd angular/
          yarn install --frozen-lockfile
          ./node_modules/.bin/ng build --configuration production --progress
          cp -r src/assets dist/bookkeeper
          cp -r src/manifest.json dist/bookkeeper

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: angular/dist/bookkeeper/

  docker:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' || github.ref == 'refs/heads/main' }}
    needs: [build]
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: build version string
        run: echo "VERSION=$(git log -n 1 --no-merges --format=format:%h angular/)" >> $GITHUB_ENV

      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact
          path: angular/dist/bookkeeper/

      - name: login to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and push image
        uses: docker/build-push-action@v6
        with:
          context: angular/
          tags: |
            ghcr.io/docqube/bookkeeper/frontend:latest
            ghcr.io/docqube/bookkeeper/frontend:${{ env.VERSION }}
          push: ${{ github.ref == 'refs/heads/main' }}
