name: go

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/go.yaml"
      - "go/**"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/go.yaml"
      - "go/**"

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup golang
        uses: actions/setup-go@v5
        with:
          go-version-file: "go/go.mod"

      - name: run tests
        run: cd go && make test

  build:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' || github.ref == 'refs/heads/main' }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup golang
        uses: actions/setup-go@v5
        with:
          go-version-file: "go/go.mod"

      - name: build backend
        env:
          GOOS: linux
          GOARCH: amd64
          CGO_ENABLED: 0
        run: cd go && make build

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: go/build/bookkeeper-api

  docker:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' || github.ref == 'refs/heads/main' }}
    needs: [build]
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: build version string
        run: echo "VERSION=$(git log -n 1 --no-merges --format=format:%h go/)" >> $GITHUB_ENV

      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact
          path: go/build/

      - name: login to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and push image
        uses: docker/build-push-action@v6
        with:
          context: go/
          tags: |
            ghcr.io/docqube/bookkeeper/backend:latest
            ghcr.io/docqube/bookkeeper/backend:${{ env.VERSION }}
          push: ${{ github.ref == 'refs/heads/main' }}
